"""empty message

Revision ID: 73087a41b629
Revises: 
Create Date: 2020-06-15 09:37:04.362072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73087a41b629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index(op.f('ix_keyword_description'), 'keyword', ['description'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_creation_date'), 'article', ['creation_date'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=True)
    op.create_index(op.f('ix_article_update_date'), 'article', ['update_date'], unique=False)
    op.create_table('article_keyword_association_table',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.keyword_id'], )
    )
    op.create_table('reference',
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_index(op.f('ix_reference_description'), 'reference', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_description'), table_name='reference')
    op.drop_table('reference')
    op.drop_table('article_keyword_association_table')
    op.drop_index(op.f('ix_article_update_date'), table_name='article')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_creation_date'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_keyword_description'), table_name='keyword')
    op.drop_table('keyword')
    # ### end Alembic commands ###
