"""unique constraint deletion for description field in Reference model

Revision ID: ab2c58dd6c83
Revises: 73087a41b629
Create Date: 2020-06-17 10:13:58.196610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2c58dd6c83'
down_revision = '73087a41b629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_description', table_name='reference')
    op.create_index(op.f('ix_reference_description'), 'reference', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_description'), table_name='reference')
    op.create_index('ix_reference_description', 'reference', ['description'], unique=1)
    # ### end Alembic commands ###
