"""deletion of Keyword model

Revision ID: b5749015dc1c
Revises: ab2c58dd6c83
Create Date: 2020-06-17 15:53:25.683860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5749015dc1c'
down_revision = 'ab2c58dd6c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_keyword_description', table_name='keyword')
    op.drop_table('keyword')
    op.drop_table('article_keyword_association_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_keyword_association_table',
    sa.Column('article_id', sa.INTEGER(), nullable=True),
    sa.Column('keyword_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.keyword_id'], )
    )
    op.create_table('keyword',
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index('ix_keyword_description', 'keyword', ['description'], unique=1)
    # ### end Alembic commands ###
